DROP SEQUENCE seq_BIMRL_FEDERATEDMODEL_ID;

DROP TABLE BIMRL_FEDERATEDMODEL;
CREATE TABLE BIMRL_FEDERATEDMODEL (
		  ProjectName varchar2(256) NOT NULL,
		  ProjectNumber varchar2(256) NOT NULL, 
		  ProjectID varchar2(22),
		  FederatedID number(10) NOT NULL UNIQUE,
		  WORLDBBOX SDO_GEOMETRY,
		  MAXOCTREELEVEL number(2),
		  LastUpdateDate date,
		  PRIMARY KEY (ProjectNumber, ProjectName)
);

INSERT INTO BIMRL_FEDERATEDMODEL (PROJECTNAME, PROJECTNUMBER, FEDERATEDID) VALUES ('Project Name', 'Project Number', 0);

CREATE OR REPLACE TRIGGER federatedID_increment
BEFORE INSERT
ON BIMRL_FEDERATEDMODEL
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT MAX(FederatedID)+1 INTO :NEW.FederatedID FROM BIMRL_FEDERATEDMODEL;
END;
/

/*
CREATE SEQUENCE seq_BIMRL_FEDERATEDMODEL_ID;
SELECT seq_BIMRL_FEDERATEDMODEL_ID.nextval INTO :NEW.FederatedID FROM dual;
*/

DROP TABLE BIMRL_OBJECTHIERARCHY;
CREATE TABLE BIMRL_OBJECTHIERARCHY (
		  IfcSchemaVer varchar2(32) NOT NULL,
		  ElementType varchar2(64) NOT NULL, 
		  ElementSubType varchar2(64) NOT NULL, 
		  Abstract number(1) DEFAULT 0, 
		  LevelsRemoved number(3)
);
CREATE INDEX IDX1_BIMRL_OBJHIER on BIMRL_OBJECTHIERARCHY (IfcSchemaVer, ElementType);
CREATE INDEX IDX2_BIMRL_OBJHIER on BIMRL_OBJECTHIERARCHY (IfcSchemaVer, ElementSubType);

CREATE OR REPLACE TYPE POINT3D AS OBJECT (
		  X	DOUBLE PRECISION,
		  Y	DOUBLE PRECISION,
		  Z	DOUBLE PRECISION
);
/

CREATE OR REPLACE TYPE MATRIX3D AS VARRAY(3) of POINT3D;
/

CREATE TABLE "COLORDICT" (
		  "ELEMENTTYPE" VARCHAR2(64) NOT NULL ENABLE, 
		  "AMBIENTINTENSITY" FLOAT(126), 
		  "DIFFUSECOLORRED" NUMBER(3,0), 
		  "DIFFUSECOLORGREEN" NUMBER(3, 0), 
		  "DIFFUSECOLORBLUE" NUMBER(3,0), 
		  "EMISSIVECOLORRED" NUMBER(3, 0), 
		  "EMISSIVECOLORGREEN" NUMBER(3,0), 
		  "EMISSIVECOLORBLUE" NUMBER(3, 0), 
		  "SHININESS" FLOAT(126), 
		  "SPECULARCOLORRED" NUMBER(3, 0), 
		  "SPECULARCOLORGREEN" NUMBER(3, 0), 
		  "SPECULARCOLORBLUE" NUMBER(3, 0), 
		  "TRANSPARENCY" FLOAT(126)) 
;
