//Drop index IDX_BIMRLELEM_GEOMMJ1_&1;
// Create Index IDX_BIMRLELEM_GEOMMJ1_&1 on BIMRL_ELEMENT_&1
//   (BODY_MAJOR_AXIS1) INDEXTYPE is MDSYS.SPATIAL_INDEX PARAMETERS ('sdo_indx_dims=3');

//Drop index IDX_BIMRLELEM_GEOMMJ2_&1;
// Create Index IDX_BIMRLELEM_GEOMMJ2_&1 on BIMRL_ELEMENT_&1
//   (BODY_MAJOR_AXIS2) INDEXTYPE is MDSYS.SPATIAL_INDEX PARAMETERS ('sdo_indx_dims=3');

//Drop index IDX_BIMRLELEM_GEOMMJ3_&1;
// Create Index IDX_BIMRLELEM_GEOMMJ3_&1 on BIMRL_ELEMENT_&1
//   (BODY_MAJOR_AXIS3) INDEXTYPE is MDSYS.SPATIAL_INDEX PARAMETERS ('sdo_indx_dims=3');

//Drop index IDX_BIMRLELEM_GEOMMJC_&1;
// Create Index IDX_BIMRLELEM_GEOMMJC_&1 on BIMRL_ELEMENT_&1
//   (BODY_MAJOR_AXIS_CENTROID) INDEXTYPE is MDSYS.SPATIAL_INDEX PARAMETERS ('sdo_indx_dims=3');
