//Drop index IDX_TOPOF_POLYGON_&1;
// Create Index IDX_TOPOF_POLYGON_&1 on BIMRL_TOPO_FACE_&1
//   (POLYGON) INDEXTYPE is MDSYS.SPATIAL_INDEX PARAMETERS ('sdo_indx_dims=3');

//Drop index IDX_TOPOF_NORMAL_&1;
// Create Index IDX_TOPOF_NORMAL_&1 on BIMRL_TOPO_FACE_&1
//   (NORMAL) INDEXTYPE is MDSYS.SPATIAL_INDEX PARAMETERS ('sdo_indx_dims=3');

//Drop Index IDX_TOPOF_CENTROID_&1;
// Create Index IDX_TOPOF_CENTROID_&1 on BIMRL_TOPO_FACE_&1
//   (CENTROID) INDEXTYPE is MDSYS.SPATIAL_INDEX PARAMETERS ('sdo_indx_dims=3');
