CREATE TABLE BIMRL_RELSPACEB_DETAIL_&1 (
		  SpaceElementID varchar2(22) NOT NULL,
		  SFACEBOUNDID varchar2(22) NOT NULL,
		  COMMMONPOINTATS SDO_GEOMETRY,
		  BoundaryElementID varchar2(22) NOT NULL,
		  BFACEBOUNDID varchar2(22) NOT NULL,
		  COMMONPOINTATB SDO_GEOMETRY,
		  Primary Key (SpaceElementID, SFaceBoundID, BoundaryElementID, BFaceBoundID)
);

ALTER TABLE BIMRL_RELSPACEB_DETAIL_&1 ADD CONSTRAINT FK_Space_det_&1 FOREIGN KEY (SpaceElementID) REFERENCES BIMRL_ELEMENT_&1 (ElementID);
ALTER TABLE BIMRL_RELSPACEB_DETAIL_&1 ADD CONSTRAINT FK_Boundaries_det_&1 FOREIGN KEY (BoundaryElementID) REFERENCES BIMRL_ELEMENT_&1 (ElementID);

